// Generated by CoffeeScript 1.7.1
(function() {
  var Blog, request;

  request = require('./request');

  module.exports = Blog = function(host, oauth) {
    this.host = host;
    this.oauth = oauth;
  };

  (function() {
    var alias, type, _i, _len, _ref, _results;
    this.info = function(fn) {
      var url;
      url = request.blogUrl('info', this);
      return request.get(url, fn);
    };
    this.avatar = function(size, fn) {
      var options, url, _ref;
      if (typeof size === 'function') {
        _ref = [size, null], fn = _ref[0], size = _ref[1];
      }
      if (size != null) {
        options = {
          type: size
        };
      }
      url = request.blogUrl('avatar', this, options);
      return request.get(url, fn);
    };
    this.followers = function(options, fn) {
      var url, _ref;
      if (typeof options === 'function') {
        _ref = [options, null], fn = _ref[0], options = _ref[1];
      }
      url = request.blogUrl('followers', this, options);
      return request.oauthGet(url, this.oauth, fn);
    };
    this.likes = function(options, fn) {
      var url, _ref;
      if (typeof options === 'function') {
        _ref = [options, null], fn = _ref[0], options = _ref[1];
      }
      url = request.blogUrl('likes', this, options);
      return request.get(url, fn);
    };
    this.posts = function(options, fn) {
      var url, _ref;
      if (typeof options === 'function') {
        _ref = [options, null], fn = _ref[0], options = _ref[1];
      }
      url = request.blogUrl('posts', this, options);
      return request.get(url, fn);
    };
    alias = function(self, type) {
      return self[type] = function(options, fn) {
        if (!options) {
          options = {};
        }
        if (!options.type) {
          options.type = type;
        }
        return this.posts(options, fn);
      };
    };
    _ref = ['text', 'quote', 'link', 'answer', 'video', 'audio', 'photo'];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      type = _ref[_i];
      _results.push(alias(this, type));
    }
    return _results;
  }).call(Blog.prototype);

}).call(this);
