// Generated by CoffeeScript 1.6.3
/*
  node-tumblr 0.2.0
  (c) 2013 Greg Wang
*/


(function() {
  var RequestUtils, qs, request;

  module.exports = RequestUtils = {};

  request = require('request');

  qs = require('querystring');

  (function() {
    this.blogUrl = function(action, self, options) {
      var params, query;
      if (options == null) {
        options = {};
      }
      params = ['http://api.tumblr.com/v2/blog/', self.host + '/' + action, options.type != null ? '/' + options.type : void 0, '?'];
      if (options.type != null) {
        delete options.type;
      }
      options.api_key = self.consumerKey;
      query = qs.stringify(options);
      params.push(query);
      return params.join('');
    };
    return this.apikeyGet = function(url, fn) {
      if (fn == null) {
        fn = function() {};
      }
      return request.get({
        url: url,
        followRedirect: false,
        json: true
      }, function(err, response, body) {
        if (!err) {
          if (response.statusCode !== 200 && response.statusCode !== 301) {
            err = body.meta.msg;
          }
        }
        return fn.call(body, err, body.response);
      });
    };
  }).call(RequestUtils);

}).call(this);
