// Generated by CoffeeScript 1.7.1
(function() {
  var Tagged, request;

  request = require('./request');

  module.exports = Tagged = function(oauth) {
    this.oauth = oauth;
  };

  (function() {
    return this.search = function(tag, options, fn) {
      var url, _ref;
      if (!tag) {
        throw new Error('The tag is required');
      }
      if (typeof options === 'function') {
        _ref = [options, {}], fn = _ref[0], options = _ref[1];
      }
      options.tag = tag;
      url = request.taggedUrl(this, options);
      return request.get(url, fn);
    };
  }).call(Tagged.prototype);

}).call(this);
