// Generated by CoffeeScript 1.6.3
(function() {
  var Tagged, request;

  request = require('./request');

  module.exports = Tagged = function(oauth) {
    var self;
    this.oauth = oauth;
    self = this;
    return function(options, fn) {
      var url;
      if (typeof options === 'string') {
        options = {
          tag: options
        };
      }
      url = request.taggedUrl(self, options);
      return request.get(url, fn);
    };
  };

}).call(this);
