// Generated by CoffeeScript 1.6.3
/*
  node-tumblr 0.1.1
  (c) 2011-2013 Alexey Simonenko, Serenity LLC.
*/


(function() {
  var Blog, qs, xhr;

  xhr = require('request');

  qs = require('querystring');

  Blog = exports.Blog = function(host, consumerKey, consumerSecret, token, tokenSecret) {
    this.host = host;
    this.consumerKey = consumerKey;
    this.consumerSecret = consumerSecret;
    this.token = token;
    return this.tokenSecret = tokenSecret;
  };

  (function() {
    var alias, request, type, urlFor, _i, _len, _ref;
    this.info = function(fn) {
      var url;
      url = urlFor('info', this);
      return request(url, fn);
    };
    this.avatar = function(size, fn) {
      var url, _ref;
      if (typeof size === 'function') {
        _ref = [size, null], fn = _ref[0], size = _ref[1];
      }
      url = urlFor('avatar', this, {
        type: size
      });
      return request(url, fn);
    };
    this.likes = function(options, fn) {
      var url, _ref;
      if (typeof options === 'function') {
        _ref = [options, null], fn = _ref[0], options = _ref[1];
      }
      url = urlFor('likes', this, options);
      return request(url, fn);
    };
    this.posts = function(options, fn) {
      var url, _ref;
      if (typeof options === 'function') {
        _ref = [options, null], fn = _ref[0], options = _ref[1];
      }
      url = urlFor('posts', this, options);
      return request(url, fn);
    };
    alias = function(self, type) {
      return self[type] = function(options, fn) {
        if (!options) {
          options = {};
        }
        if (!options.type) {
          options.type = type;
        }
        return this.posts(options, fn);
      };
    };
    _ref = ['text', 'quote', 'link', 'answer', 'video', 'audio', 'photo'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      type = _ref[_i];
      alias(this, type);
    }
    urlFor = function(action, self, options) {
      var params, query;
      if (options == null) {
        options = {};
      }
      params = ['http://api.tumblr.com/v2/blog/', self.host + '/' + action, options.type != null ? '/' + options.type : void 0, '?'];
      if (options.type != null) {
        delete options.type;
      }
      options.api_key = self.consumerKey;
      query = qs.stringify(options);
      if (query !== '') {
        params.push(query);
      }
      return params.join('');
    };
    return request = function(url, fn) {
      if (fn == null) {
        fn = function() {};
      }
      return xhr({
        url: url,
        followRedirect: false
      }, function(error, response, body) {
        var err;
        try {
          body = JSON.parse(body);
          if (response.statusCode !== 200 && response.statusCode !== 301) {
            err = body.meta.msg;
          }
        } catch (_error) {
          error = _error;
          err = "Invalid Response: " + error;
        }
        return fn.call(body, err, body.response);
      });
    };
  }).call(Blog.prototype);

}).call(this);
