// Generated by CoffeeScript 1.6.3
/*
  node-tumblr 0.2.0
  (c) 2013 Greg Wang
*/


(function() {
  var RequestUtils, User, qs;

  RequestUtils = require('./requestutils');

  qs = require('querystring');

  module.exports = User = function(consumer_key, consumer_secret, token, token_secret) {
    this.consumer_key = consumerKey;
    this.consumer_secret = consumerSecret;
    this.token = token;
    return this.token_secret = tokenSecret;
  };

  (function() {
    return this.info = function(fn) {
      var url;
      url = RequestUtils.userUrl('info', this);
      return RequestUtils.oauthGet(url, this, fn);
    };
  }).call(User.prototype);

}).call(this);
