// Generated by CoffeeScript 1.6.3
/*
  node-tumblr 0.2.0
  (c) 2013 Greg Wang
*/


(function() {
  var RequestUtils, User, qs;

  RequestUtils = require('./requestutils');

  qs = require('querystring');

  module.exports = User = function(consumer_key, consumer_secret, token, token_secret) {
    this.consumer_key = consumer_key;
    this.consumer_secret = consumer_secret;
    this.token = token;
    return this.token_secret = token_secret;
  };

  (function() {
    this.info = function(fn) {
      var url;
      url = RequestUtils.userUrl('info', this);
      return RequestUtils.oauthGet(url, this, fn);
    };
    this.dashboard = function(options, fn) {
      var url, _ref;
      if (typeof options === 'function') {
        _ref = [options, null], fn = _ref[0], options = _ref[1];
      }
      url = RequestUtils.userUrl('dashboard', this, options);
      return RequestUtils.oauthGet(url, this, fn);
    };
    this.likes = function(options, fn) {
      var url, _ref;
      if (typeof options === 'function') {
        _ref = [options, null], fn = _ref[0], options = _ref[1];
      }
      url = RequestUtils.userUrl('likes', this, options);
      return RequestUtils.oauthGet(url, this, fn);
    };
    return this.following = function(options, fn) {
      var url, _ref;
      if (typeof options === 'function') {
        _ref = [options, null], fn = _ref[0], options = _ref[1];
      }
      url = RequestUtils.userUrl('following', this, options);
      return RequestUtils.oauthGet(url, this, fn);
    };
  }).call(User.prototype);

}).call(this);
